version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi_app  # Path relative to docker-compose.yml
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    restart: always

  streamlit:
    build:
      context: ./streamlit_app  # Path relative to docker-compose.yml
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    depends_on:
      - fastapi
    restart: always
